name: unisrec
channels:
  - defaults
  - conda-forge
  - torch
dependencies:
  - python=3.9
  - pip
  - pip:
    - accelerate
    - torch
    - torchaudio
    - torchvision
    - transformers
    - sentence-transformers
    - scikit-learn
    - pandas
    - numpy
    - tqdm
    - psutil
    - pandas-gbq
    - recbole
    - peft
    - kfp