data_path: 'data/finetune'
benchmark_filename: [train, valid, test]
stage: finetune
parameter_efficient: inductive
topk: [10, 50]
metrics: [Hit, NDCG]
valid_metric: NDCG@10
eval_batch_size: 1024
eval_step: 1
loss_type: 'CE'
learning_rate: 0.001
train_neg_sample_args:

epochs: 50
stopping_step: 10
save_step: 5

device: cuda
checkpoint_dir: saved
