hidden_size: 300
layer_norm_eps: 1e-12
dropout_prob: 0.1
hidden_dropout_prob: 0.1
attn_dropout_prob: 0.1
num_blocks: 2
num_heads: 12
feed_forward_size: 256
hidden_act: gelu
loss_type: 'BPR'
init_normal_std: 0.02
bpr_gamma: 0.1


